export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_USER_FACE_RECORD = 'SET_USER_FACE_RECORD'
export const DELETE_RECORD_IMG_BY_ID = 'DELETE_RECORD_IMG_BY_ID'
export const SET_ALL_USER_FACE_RECORD = 'SET_ALL_USER_FACE_RECORD'
export const SET_RECORD_OPEN_STATUS = 'SET_RECORD_OPEN_STATUS'

